image: arusir/courseware-template:0.1

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  - export CI_PROJECT_NAME CI_PROJECT_NAMESPACE CI_PROJECT_URL
  - envsubst < _config.yml > _final_config.yml
  - cat _final_config.yml
  - bundle exec jekyll build -d public --config _final_config.yml
  artifacts:
    paths:
    - public
  only:
  - main
  - original-docker-image
