image: ruby:2.7.2

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install
  - apt-get update
  - apt-get -y install pandoc
  - apt-get -y install texlive-latex-base
  - apt-get -y install texlive-latex-extra

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - main
  - slides-build-step
